# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
	config.vm.define "master" do |master|
		master.vm.hostname = "master.vagrant"
		master.vm.network "private_network", ip: "192.168.122.2", virtualbox__intnet: "in1"
	end
	config.vm.define "host" do |host|
		host.vm.hostname = "host.vagrant"
		host.vm.network "private_network", ip: "192.168.122.3", virtualbox__intnet: "in1"
	end
end
